apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://admin:master123@postgres:5432/postgres?schema=public"
  ACCESS_TOKEN_SECRET_KEY: "EAJYjNJUnRGJ6uq1YfGw4NG1pd1z102J"
  REFRESH_TOKEN_SECRET_KEY: "LcnlpiuHIJ6eS51u1mcOdk0P49r2Crwu"

