apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  NODE_ENV: "local"
  APP_NAME: "@backendworks/auth"
  APP_CORS_ORIGINS: "*"
  APP_DEBUG: "true"
  NEST_NO_WATCH: "true"

  HTTP_ENABLE: "true"
  HTTP_PORT: "9001"
  HTTP_VERSIONING_ENABLE: "true"
  HTTP_VERSION: "1"

  SENTRY_DSN: ""

  ACCESS_TOKEN_EXPIRED: "1d"
  REFRESH_TOKEN_EXPIRED: "7d"

  REDIS_URL: "redis://redis:6379"
  REDIS_KEY_PREFIX: "auth:"
  REDIS_TTL: "3600"

  GRPC_URL: "0.0.0.0:50051"
  GRPC_PACKAGE: "auth"

