apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config
data:
  APP_NAME: "@backendworks/post"
  APP_CORS_ORIGINS: "*"
  APP_DEBUG: "true"
  NEST_NO_WATCH: "true"

  HTTP_ENABLE: "true"
  HTTP_PORT: "9002"

  GRPC_URL: "0.0.0.0:50052"
  GRPC_PACKAGE: "post"

  REDIS_URL: "redis://redis:6379"
  REDIS_KEY_PREFIX: "post:"
  REDIS_TTL: "3600"

  DATABASE_URL: "postgresql://admin:master123@postgres:5432/postgres?schema=public"

  GRPC_AUTH_URL: "auth-service:50051"

